Responses.py cleanup
DesertBot/DesertBot pull request #186
Opened 2019-09-27 19:54 UTC by HubbeKing

It's TIME to clean this bad boi up some.

- [x] get Boops out into its own module
- [ ] get Animals out into its own module
- [ ] clean up what remains into a WeirdResponses module or something
- [ ] store responses in bot storage?

Help appreciated

2019-09-27 20:46 UTC, HubbeKing commented
H'okay, this is about as good as I can make it right now. Might look at the Weirder responses later, but feel free to finish up if you like.

2019-09-28 08:31 UTC, Heufneutje approved these changes

2019-09-28 19:12 UTC, HubbeKing commented
Okay, I did a basic refactor on the remaining stuff in Responses.py
(I also threw out the Ponies response, as the link it had was a 404, and the DuctTape response, as that hasn't been relevant for YEARS. Feel free to prune further in datastore_default.json)

This is now about done, I think? Unless either of you have Good Ideas for how to make this less gross?

2019-09-28 23:09 UTC, StarlitGhost commented on desertbot/datastore_default.json
> +      "20": "{user} is {article} CRITICAL {animal}!"
"it's a lovely day in the chat, and {user} is a horrible goose." for critical

2019-09-28 23:11 UTC, StarlitGhost commented on desertbot/modules/automatic/Animals.py
> +            "20": "{user} is {article} CRITICAL {animal}!"
I think this article should always be 'a' since it's before CRITICAL

2019-09-28 23:17 UTC, StarlitGhost requested changes
I like it, both of the new modules look good. Couple of minor changes as already noted.

So much has changed in Reponses.py that it's hard to read the code through the diff, but I think those phrase responses are always going to be a bit janky given the weirdness of the matching.

2019-09-29 08:41 UTC, HubbeKing commented
There we go. All cleaned up and hopefully easier to read now. Only thing I can think of that is removing the ResponseObject class and just using a dict instead, but that feels like a lot of work for very little benefit.

(As fun as having self.responses just be a dict of responseName to the stuff in self.bot.storage['responses'] would be, I think the ResponseObject class adds a lot of useful helper methods.)

2019-09-29 15:05 UTC, merged