Separate data files for each module
DesertBot/DesertBot pull request #190
Opened 2019-10-04 18:46 UTC by HubbeKing

Okay! So as I said in issue #189 , I had an idea for having a separate .json file for each module that needs to store things.

This is how I implemented it, along with some REAL hacky code in ModuleInterface to automatically import existing legacy data.

FYI - files in data/defaults _ALWAYS_ overwrite data in data/<network> on bot startup, this is because I wanted us to be able to modify stuff like Responses and Animals without having to SSH into a server and poke at a file, we can just edit on Github and when the bot updates it'll figure itself out.

This runs and appears to work, but there are almost CERTAINLY edge-cases I didn't think of. I would appreciate it if we could do some manual testing - especially with adding things to storage during runtime, I probably forgot some stuff there.

Fancy stuff:
- modules that need storage can just access self.storage as if it were a dict. It'll work, and it'll get saved to disk automatically - see DataStore.__set__() and DataStore.save()

TODOs that I know of:
[ ] changes to non-defaults storage files during runtime need to get saved to the corresponding defaults-file, if one exists. I didn't do this bit yet. I spent like 2 hours coding and am wonked out rn.
[ ] Tests. So many tests.
[ ] Getting rid of the legacy data file (desertbot.json) when we've imported all we need from it (this can probably just be a manual thing
[ ] Tests for each module that uses storage, so we know nothing broke

2019-10-07 07:29 UTC, Heufneutje approved these changes

2019-10-14 18:36 UTC, HubbeKing commented
This is now about as good as I can make it. Ready to merge.

2019-10-18 13:27 UTC, StarlitGhost requested changes
Looks good, 2 minor tweaks

2019-10-18 13:27 UTC, StarlitGhost commented on desertbot/modules/commands/FFXIV.py
> +        self.charLinkStorage = self.storage["chars"]
we could just use self.storage["chars"] directly. I'm not sure why I was doing this anyway, to be honest...

2019-10-18 13:27 UTC, StarlitGhost commented on desertbot/modules/admin/Storage.py
> +        moduleNames = [mh.caseMap[name.lower()] for name in message.parameterList[1:] if name.lower() in mh.caseMap]
maybe a function for this since it's repeated 4 times

2019-10-18 13:33 UTC, Heufneutje requested changes

2019-10-18 13:33 UTC, Heufneutje commented on desertbot/datastore.py
> +            tmpFile = "{}.tmp".format(self.storagePath)
This could probably use the new string format style since it's used everywhere else in this PR.

2019-10-18 13:33 UTC, Heufneutje commented on desertbot/datastore.py
> +                tmpFile = "{}.tmp".format(self.defaultsPath)
This could probably use the new string format style since it's used everywhere else in this PR.

2019-10-18 15:40 UTC, HubbeKing commented
Changes done as requested, only thing one should still check is like the FFXIV module, as the change might've wonked up things some

2019-10-19 15:28 UTC, Heufneutje approved these changes
Looks good to me.

2019-10-22 13:42 UTC, StarlitGhost approved these changes
looks good to me!

2019-10-22 13:43 UTC, merged